services:
  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - mesh
    ports:
      - 8080:8080
      - 8081:8081

  upstream-service:
    image: golang:1.19
    working_dir: /workspace
    command:
    - bash
    - -c
    - 'go run ./cmd/server/*.go'
    volumes:
      - ..:/workspace
    networks:
      - mesh
    ports:
      - 8082:8082

networks:
  mesh: {}